### ISSUE TITLE
[ Global ] Voyage Regular vs. Bold.

### ISSUE THREAD

**Issue by margauxlepierres** [phillipmalboeuf/dlc#1]
Here are the updated files for Voyage Regular vs. Bold.

[Voyage_Regular (1).zip](https://github.com/phillipmalboeuf/dlc/files/5631029/Voyage_Regular.1.zip)

**Comment by phillipmalboeuf** [comment]
Ah my bad @margauxlepierres, this wasn't a matter of file, I just missed a line of css
