### ISSUE TITLE
[Casestudy] Increase to full width of browser

### ISSUE THREAD

**Issue by margauxlepierres** [phillipmalboeuf/dlc#20]
Can we increase the width of the case study to touch the edges of the browser?

![image](https://user-images.githubusercontent.com/7320077/101071736-0107e700-356b-11eb-8377-bc931e5b6b91.png)

**Comment by phillipmalboeuf** [comment]
I don't quite agree with this one @margauxlepierres, it gives people an alternative way to close the popup.

**Comment by margauxlepierres** [comment]
Oh, that's a really good point! Thanks for pushing back on that @phillipmalboeuf.
