### ISSUE TITLE
[Music] 

### ISSUE THREAD

**Issue by margauxlepierres** [phillipmalboeuf/dlc#29]
Totally on board with the click feature for music...

On hover, I'm noticing that I hear a strange whitenoise/interferance sound like when a radio station goes out of service or when you are plugging an AUX cord into some speakers?  (On Chrome) [Example here](https://www.dropbox.com/s/dgsou7s400j6e2l/DLC_Noises.mov?dl=0)

And I'm not hearing any sound when clicking right now?

**Comment by phillipmalboeuf** [comment]
Aiight will implement click instead of hover, but Is it waves that you're hearing @margauxlepierres? I put up a random song for testing and it starts with waves hahah! Would you have a sample of what Danielle would like to put up?
