### ISSUE TITLE
[MUSIC] Remove Icon, Introduce Underline

### ISSUE THREAD

**Issue by margauxlepierres** [phillipmalboeuf/dlc#33]
Can we remove the headphone icon next to the Boundless, and introduce an underline. 

And.. I haven't showed these to Dani yet because I wanted to get your opinion first... Is it feasible to introduce a little 'turn it up' image after click — Or a little 'player' center bottom that would also allow you to pause? 

![image](https://user-images.githubusercontent.com/7320077/101371661-028e2380-3879-11eb-8114-2288982d2856.png)

**Comment by phillipmalboeuf** [comment]
I like that little player! Will get it done @margauxlepierres
